=== nyankosama/cobar/server/src/main/resources/servers.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!--
         - Copyright 1999-2012 Alibaba Group.
         -
         - Licensed under the Apache License, Version 2.0 (the "License");
         - you may not use this file except in compliance with the License.
         - You may obtain a copy of the License at
         -
         -      http://www.apache.org/licenses/LICENSE-2.0
         -
         - Unless required by applicable law or agreed to in writing, software
         - distributed under the License is distributed on an "AS IS" BASIS,
         - WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         - See the License for the specific language governing permissions and
         - limitations under the License.
        -->
        <!ELEMENT cluster (groups*,tables*)>
            <!ELEMENT groups (group*) >
                <!ELEMENT group (name, servers, migrations*) >
                    <!ELEMENT name (#PCDATA) >
                    <!ELEMENT servers (server+) >
                        <!ELEMENT server (id, description*, host, port, db_name, user, password, online, capacity, size) >
                            <!ELEMENT id (#PCDATA) >
                            <!ELEMENT description (#PCDATA) >
                            <!ELEMENT host (#PCDATA) >
                            <!ELEMENT port (#PCDATA) >
                            <!ELEMENT db_name (#PCDATA) >
                            <!ELEMENT user (#PCDATA) >
                            <!ELEMENT password (#PCDATA) >
                            <!ELEMENT online (#PCDATA) >
                            <!ELEMENT capacity (#PCDATA) >
                            <!ELEMENT size (#PCDATA) >
                    <!ELEMENT migrations (migration+) >
                        <!ELEMENT migration (groupName, from, to) >
                            <!ELEMENT groupName (#PCDATA) >
                            <!ELEMENT from (#PCDATA) >
                            <!ELEMENT to (#PCDATA) >
            <!ELEMENT tables (table+) >
                <!ELEMENT table (table_name, split_columns, master_group, brother_group) >
                    <!ELEMENT table_name (#PCDATA) >
                    <!ELEMENT split_columns (#PCDATA) >
                    <!ELEMENT master_group (#PCDATA) >
                    <!ELEMENT brother_group (#PCDATA) >




        <!--<!ELEMENT schema (table*)>-->
        <!--<!ATTLIST schema name NMTOKEN #REQUIRED>-->
        <!--<!ATTLIST schema dataNode CDATA #IMPLIED>-->
        <!--<!ATTLIST schema group CDATA #IMPLIED>-->
        <!--<!ATTLIST schema keepSqlSchema NMTOKEN #IMPLIED>-->
        <!--<!ELEMENT table (property*)>-->
        <!--<!ATTLIST table name CDATA #REQUIRED>-->
        <!--<!ATTLIST table dataNode CDATA #REQUIRED>-->
        <!--<!ATTLIST table rule NMTOKEN #IMPLIED>-->
        <!--<!ATTLIST table ruleRequired NMTOKEN #IMPLIED>-->

        <!--<!ELEMENT dataNode (property+)>-->
        <!--<!ATTLIST dataNode name NMTOKEN #REQUIRED>-->

        <!--<!ELEMENT dataSource (property+)>-->
        <!--<!ATTLIST dataSource name NMTOKEN #REQUIRED>-->
        <!--<!ATTLIST dataSource type NMTOKEN #REQUIRED>-->

        <!--<!ELEMENT property ( #PCDATA | bean | dataSourceRef | location )*>-->
        <!--<!ATTLIST property name NMTOKEN #REQUIRED>-->

        <!--<!ELEMENT bean (property*)>-->
        <!--<!ATTLIST bean name NMTOKEN #IMPLIED>-->
        <!--<!ATTLIST bean class NMTOKEN #REQUIRED>-->

        <!--<!ELEMENT dataSourceRef (#PCDATA)>-->
        <!--<!ELEMENT location (#PCDATA)>-->

=== nyankosama/cobar/server/assembly/conf/servers.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cluster SYSTEM "servers.dtd">
<cluster>
    <groups>
        <group>
            <name>group1</name>
            <servers>
                <server>
                    <id>1</id>
                    <description></description>
                    <host>localhost</host>
                    <port>3306</port>
                    <db_name>test_1</db_name>
                    <user>root</user>
                    <password></password>
                    <online>true</online>
                    <capacity>1000000</capacity>
                    <!-- 最大容量 -->
                    <size>123456</size>
                    <!-- 当前容量 -->
                </server>
                <server>
                    <id>2</id>
                    <description></description>
                    <host>localhost</host>
                    <port>3306</port>
                    <db_name>test_2</db_name>
                    <user>root</user>
                    <password></password>
                    <online>true</online>
                    <capacity>1000000</capacity>
                    <!-- 最大容量 -->
                    <size>654321</size>
                    <!-- 当前容量 -->
                </server>
                <server>
                    <id>3</id>
                    <description></description>
                    <host>localhost</host>
                    <port>3306</port>
                    <db_name>test_3</db_name>
                    <user>root</user>
                    <password></password>
                    <online>true</online>
                    <capacity>1000000</capacity>
                    <!-- 最大容量 -->
                    <size>654321</size>
                    <!-- 当前容量 -->
                </server>
            </servers>
        </group>
    </groups>
    <tables>
        <table>
            <table_name>user</table_name>
            <split_columns> <!-- 分表字段 -->
                <column>id</column>
            </split_columns>
            <master_group>group1</master_group>
            <brother_group>group1</brother_group>
            <!-- 热备份的group -->
        </table>
        <table>
            <table_name>account</table_name>
            <split_columns>
                <column>id</column>
            </split_columns>
            <master_group>group1</master_group>
            <brother_group>group1</brother_group>
        </table>
    </tables>
</cluster>
